import { ArrowLeft } from "lucide-react";
import { useNavigate } from "react-router-dom";
function FAQ() {
  const navigate = useNavigate();
  return (
    <section className="min-h-screen bg-[#050816] text-white px-6 py-20">
      <button
  onClick={() => navigate(-1)}
  className="
  flex
  items-center
  gap-2
  mb-8
  px-5
  py-3
  rounded-2xl
  bg-white/10
  backdrop-blur-xl
  border
  border-white/10
  hover:border-cyan-400
  hover:bg-cyan-500/10
  transition-all
"
>
  <ArrowLeft size={20} />
  Back
</button>

      <div className="max-w-5xl mx-auto">

        <h1 className="text-5xl font-black mb-10">
          Frequently Asked Questions
        </h1>

        <div className="space-y-10">

          <div>
            <h2 className="text-2xl font-semibold">
              Is RouteCraft free to use?
            </h2>

            <p className="text-slate-300 mt-3">
              Yes. RouteCraft can be used free for creating AI-powered travel itineraries.
            </p>
          </div>

          <div>
            <h2 className="text-2xl font-semibold">
              Are itineraries generated by AI?
            </h2>

            <p className="text-slate-300 mt-3">
              Yes. Every itinerary is generated using AI based on your travel preferences.
            </p>
          </div>

          <div>
            <h2 className="text-2xl font-semibold">
              Can I save my trips?
            </h2>

            <p className="text-slate-300 mt-3">
              Yes. Logged-in users can save and manage their trips.
            </p>
          </div>

        </div>

      </div>

    </section>
  );
}

export default FAQ;